on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  Check-Branch:
    # see https://stackoverflow.com/a/77727776
    runs-on: ubuntu-latest
    outputs:
      is_on_main: contains(${{ steps.check_step.outputs.branches }}, 'main')
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Current Branch
      id: check_step
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branches="$(echo ${raw//origin\//} | tr -d '\n')"
        echo "{name}=branches" >> $GITHUB_OUTPUT
        echo "Branches where this tag exists : $branches."
  Get-Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.output.VERSION }}
    steps:
    - id: get-version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
    - name: debug
  Extensions:
    name: "Publish Extensions"
    needs: [Check-Branch, Get-Version]
    if: ${{ needs.Check-Branch.outputs.is_on_main }}
    uses: ./.github/workflows/NuGet.yml
    with:
      project_path: "./Extensions/Extensions.csproj"
      version: ${{ needs.Get-Version.outputs.version }}
    secrets:
      nuget_key: ${{ secrets.NUGET_API_KEY }}
