# see https://stackoverflow.com/a/77727776
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      is_branch:
        value: ${{ jobs.Check-Branch.outputs.is_branch }}
jobs:
  Get-Branch:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-branch.outputs.branches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Branch
        id: get-branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo ${raw//origin\//} | tr -d '\n')"
          echo "{name}=branches" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branches."
  Check-Branch:
    runs-on: ubuntu-latest
    needs: Get-Branch
    outputs:
      is_branch: contains(${{ needs.check.outputs.branch }}, ${{ inputs.branch }})
    
