on:
  workflow_dispatch:
    inputs:
      project_path:
        required: true
        type: string
jobs:
  dispatch:
    uses: ./.github/workflows/NuGet.yml
    with:
      project_path: ${{ inputs.project_path }}
    secrets:
      nuget_key: ${{ secrets.NUGET_API_KEY }}
      
