on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
jobs:
  publish-nuget:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Build
      run: dotnet pack ${{ inputs.project_path }} --configuration Release --output .
    - name: Peek
      run: dir
      
    
  
