on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
    secrets:
      nuget_key:
        required: true
jobs:
  publish-nuget:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      packages: write
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build ${{ inputs.project_path }} --configuration Release
    - name: Pack
      run: dotnet pack ${{ inputs.project_path }} --configuration Release --no-build --output .
    - name: Peek
      run: dir
    - name: Publish
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.nuget_key }}
      
    
  
